# permissions for end users to view probes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: probe-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: probe-controller
    app.kubernetes.io/part-of: probe-controller
    app.kubernetes.io/managed-by: kustomize
  name: probe-viewer-role
rules:
- apiGroups:
  - probe.probe.k8s
  resources:
  - probes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - probe.probe.k8s
  resources:
  - probes/status
  verbs:
  - get
