---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - probe.probe.k8s
  resources:
  - probes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - probe.probe.k8s
  resources:
  - probes/finalizers
  verbs:
  - update
- apiGroups:
  - probe.probe.k8s
  resources:
  - probes/status
  verbs:
  - get
  - patch
  - update
